# -*- coding: utf-8 -*-
"""numpy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bEYqcsOk2n8w1D0o_ZiB9-7T4gSTV7rL
"""

import numpy as np

list_1d = [5,3,8]

np.array(list_1d)

list_2d = [[3,7,5],[3,6,7]]

np.array(list_2d)

np.arange(2,10)

np.arange(2,10,2)

np.linspace(1,10,5)

np.linspace((1,1),(10,5),10)

np.random.rand(4)

np.random.rand(3,4)

np.random.randn(5)

np.random.randn(6,4)

np.zeros(4)

np.zeros((3,5))

np.ones(4)

np.ones((3,4))

np.eye(4)

my_array =np.random.randn(12)

my_array

my_array.shape

my_array.reshape(6,2)

my_array = np.arange(3,9)

my_array

my_array[2]

my_array[2:4]

my_array[:5]

my_array[2:]

my_array[-1]

my_array[:-2]

slice_my_array = my_array[1:3]

slice_my_array

slice_my_array[:]= 25

slice_my_array

my_array

copy_my_array = my_array.copy()

copy_my_array

copy_my_array[1]= 10

copy_my_array

my_array

my_2d_array = np.array([[2,3,4],[3,4,6],[11,22,33]])

my_2d_array

my_2d_array[1]

my_2d_array[1][2]

my_2d_array[2,1]

my_2d_array[:,2]

my_2d_array[:2,1:]

rand_array = np.random.randn(10)

rand_array

rand_array > 0

bool = rand_array > 0

bool

rand_array[bool == True]

rand_array[rand_array > 1]

random_2d_array = np.random.randn(15).reshape(3,5)

random_2d_array

bool_2d_array = random_2d_array > 0

bool_2d_array

random_2d_array[bool_2d_array]

bool_2d_array[:,1]

random_2d_array[bool_2d_array[:,1]]

bool_2d_array[1,:]

array = np.arange(3,13)

array

array + 5

array - 3

array / 5

array * 6

array ** 2

array ** (1/2)

array_2 = np.arange(7,17)

array_2

array

array + array_2

array - array_2

array / array_2

array * array_2



array_2d = np.array([[2,6,4],[7,5,3],[1,8,9]])

array_2d

array_2d.dot(array_2d)

array_2d.T

array_2d.sum()

array_2d.sum(axis = 0)

array_2d.sum(axis = 1)

array_2d.mean()

array_2d.std()

array_2d = np.array([[2,6,4],[7,5,3],[1,8,9]])

array_2d

np.mod(array_2d,4)

np.sin(array_2d)

np.cos(array_2d)

np.greater(array_2d,8)

array_2d

np.less(array_2d,3)

np.logical_or(np.greater(array_2d,8),np.less(array_2d,3))

np.logical_or(array_2d > 8,array_2d < 3)

np.logical_and(array_2d > 3,array_2d < 8)

array_2d

"""| #  | Topic                       | Functions / Concepts Covered | What You Learned                                                                                                            | Example                                     |                          |
| -- | --------------------------- | ---------------------------- | --------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------- | ------------------------ |
| 1  | **Creating NumPy Arrays**   | `np.array()`                 | Convert Python lists into NumPy arrays                                                                                      | `np.array([1,2,3])`                         |                          |
| 2  | **1D Arrays**               | `np.array()`                 | Create one-dimensional arrays                                                                                               | `np.array([10,20,30])`                      |                          |
| 3  | **2D Arrays**               | `np.array()`                 | Create arrays/matrices using nested lists                                                                                   | `np.array([[1,2],[3,4]])`                   |                          |
| 4  | **Array Generation**        | `np.arange()`                | Generate values using start, stop and step                                                                                  | `np.arange(1,10,2)`                         |                          |
| 5  | **Evenly Spaced Values**    | `np.linspace()`              | Generate a fixed number of evenly spaced values                                                                             | `np.linspace(1,10,5)`                       |                          |
| 6  | **Random Arrays**           | `np.random.rand()`           | Generate random values between 0 and 1 using uniform distribution                                                           | `np.random.rand(2,3)`                       |                          |
| 7  | **Normal Random Arrays**    | `np.random.randn()`          | Generate normally distributed random values centered around 0                                                               | `np.random.randn(2,3)`                      |                          |
| 8  | **Array of Ones**           | `np.ones()`                  | Create arrays filled with `1`                                                                                               | `np.ones((2,3))`                            |                          |
| 9  | **Array of Zeros**          | `np.zeros()`                 | Create arrays filled with `0`                                                                                               | `np.zeros((2,3))`                           |                          |
| 10 | **Identity Matrix**         | `np.eye()`                   | Create an identity matrix                                                                                                   | `np.eye(3)`                                 |                          |
| 11 | **Reshaping**               | `.reshape()`                 | Change array dimensions without changing element order                                                                      | `arr.reshape(2,3)`                          |                          |
| 12 | **Indexing**                | `arr[index]`                 | Access individual elements; indexing starts at `0`                                                                          | `arr[2]`                                    |                          |
| 13 | **Negative Indexing**       | Negative indices             | Access elements from the end                                                                                                | `arr[-1]`                                   |                          |
| 14 | **2D Indexing**             | `arr[row,column]`            | Access a specific element using row and column                                                                              | `arr[1,2]`                                  |                          |
| 15 | **Slicing**                 | `arr[start:stop]`            | Extract a range; upper bound is excluded                                                                                    | `arr[1:4]`                                  |                          |
| 16 | **Negative Slicing**        | Negative indices + slicing   | Slice arrays from the end                                                                                                   | `arr[-3:]`                                  |                          |
| 17 | **2D Slicing**              | Row/column slicing           | Extract rows, columns or submatrices                                                                                        | `arr[0:2,1:3]`                              |                          |
| 18 | **Slice Reference**         | Slicing behavior             | A slice can share underlying data with the original array                                                                   | `b = arr[1:4]`                              |                          |
| 19 | **Copying Arrays**          | `.copy()`                    | Create an independent copy of an array                                                                                      | `b = arr.copy()`                            |                          |
| 20 | **Assignment vs Copy**      | `b = arr` vs `.copy()`       | Assignment creates a reference; `.copy()` creates separate data                                                             | `b = arr.copy()`                            |                          |
| 21 | **Boolean Indexing**        | Boolean masks                | Select elements based on conditions                                                                                         | `arr[arr > 0]`                              |                          |
| 22 | **Boolean Mask**            | `mask = condition`           | Create a Boolean array and use it for filtering                                                                             | `mask = arr > 0`                            |                          |
| 23 | **2D Boolean Filtering**    | Boolean indexing             | Filter values from 2D arrays; selected results can become 1D                                                                | `arr[arr > 5]`                              |                          |
| 24 | **Scalar Operations**       | `+`, `-`, `*`, `/`           | Apply an operation to every element                                                                                         | `arr + 5`                                   |                          |
| 25 | **Power Operations**        | `**`                         | Raise every array element to a power                                                                                        | `arr ** 2`                                  |                          |
| 26 | **Square Root**             | `np.sqrt()`                  | Calculate square root element-wise                                                                                          | `np.sqrt(arr)`                              |                          |
| 27 | **Element-wise Operations** | `+`, `-`, `*`, `/`           | Perform operations between corresponding elements of arrays                                                                 | `a + b`                                     |                          |
| 28 | **Division by Zero**        | Array division               | Division by zero in NumPy can produce warnings and `NaN`/infinite values rather than behaving like ordinary Python division | `a / 0`                                     |                          |
| 29 | **Dot Product**             | `np.dot()`                   | Calculate dot product / matrix multiplication                                                                               | `np.dot(a,b)`                               |                          |
| 30 | **Matrix Multiplication**   | Dot product                  | Multiply matrices according to row × column rules                                                                           | `np.dot(A,B)`                               |                          |
| 31 | **Transpose**               | `.T` / transpose concept     | Convert rows into columns and columns into rows                                                                             | `arr.T`                                     |                          |
| 32 | **Sum**                     | `np.sum()` / `arr.sum()`     | Calculate the sum of array elements                                                                                         | `np.sum(arr)`                               |                          |
| 33 | **Average / Mean**          | `np.mean()` / `arr.mean()`   | Calculate the average                                                                                                       | `np.mean(arr)`                              |                          |
| 34 | **Standard Deviation**      | `np.std()` / `arr.std()`     | Measure the spread of values around the mean                                                                                | `np.std(arr)`                               |                          |
| 35 | **Modulo**                  | `%` / `np.mod()`             | Calculate remainder element-wise                                                                                            | `np.mod(arr,2)`                             |                          |
| 36 | **Sine**                    | `np.sin()`                   | Calculate sine element-wise                                                                                                 | `np.sin(arr)`                               |                          |
| 37 | **Universal Functions**     | NumPy ufuncs                 | Apply mathematical functions element-by-element                                                                             | `np.sqrt(arr)`, `np.sin(arr)`               |                          |
| 38 | **Logical Conditions**      | `>`, `<`                     | Create Boolean conditions for filtering                                                                                     | `arr > 8`                                   |                          |
| 39 | **Logical OR**              | `                            | ` / logical OR                                                                                                              | Select elements satisfying either condition | `(arr > 8) \| (arr < 3)` |

"""